require('mini.surround').setup()
require('mini.comment').setup()
require('mini.pairs').setup()
require('mini.ai').setup()
require('mini.icons').setup()

require('mini.files').setup()
vim.keymap.set('n', '<leader>-', function()
  MiniFiles.open()
end, { desc = 'Open MiniFiles' })